version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres_customer:
    image: postgres:15
    environment:
      POSTGRES_DB: customer_service_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - customer_pg:/var/lib/postgresql/data

  postgres_order:
    image: postgres:15
    environment:
      POSTGRES_DB: order_service_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - order_pg:/var/lib/postgresql/data

  customer_service:
    build: ./customer_service
    command: bash -c "rails db:create db:migrate db:seed && rails s -b 0.0.0.0"
    volumes:
      - ./customer_service:/app
    ports:
      - "3001:3000"
    environment:
      DATABASE_HOST: postgres_customer
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
    depends_on:
      postgres_customer:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  customer_consumer:
    build: ./customer_service
    command: bash -c "bin/consume_events"
    volumes:
      - ./customer_service:/app
    environment:
      DATABASE_HOST: postgres_customer
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      customer_service:
        condition: service_started
    restart: unless-stopped
    
  order_service:
    build: ./order_service
    command: bash -c "rails db:prepare  && rails s -b 0.0.0.0"
    volumes:
      - ./order_service:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres_order
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
      CUSTOMER_SERVICE_URL: http://customer_service:3000
    depends_on:
      postgres_order:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  customer_pg:
  order_pg: