
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USER", "juanguauque") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>


development:
  <<: *default
  database: order_service_development

test:
  <<: *default
  database: order_service_test
