
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: juanguauque
  password: password


development:
  <<: *default
  database: order_service_development

test:
  <<: *default
  database: order_service_test
